# Базовый образ

FROM node:20-alpine AS development

WORKDIR /app

# Копируем зависимости
COPY package.json package-lock.json ./
RUN npm install

# Устанавливаем NX глобально
RUN npm install -g nx

# Копируем всё (исходный код будет перезаписан volume)
COPY . .
